# tests/testthat/test-inverse-categories.R
#
# Validation tests for inverse_categories() accessor.
# Generated by Tester pipeline from test-spec.md (inverse-categories-2026-04-21).
# Tester did NOT read spec.md or implementation.md.
#
# Tests: TC-INV-1, TC-INV-2, TC-INV-3, TC-INV-4

# ---------------------------------------------------------------------------
# TC-INV-1: Accessor returns a character vector
# ---------------------------------------------------------------------------

test_that("inverse_categories() returns a character vector", {
  result <- inverse_categories()
  expect_true(is.character(result))
})

# ---------------------------------------------------------------------------
# TC-INV-2: Accessor returns exactly the eight starter elements
# ---------------------------------------------------------------------------

test_that("inverse_categories() contains the starter list", {
  result <- inverse_categories()
  starter <- c("ERA", "WHIP", "FIP", "xFIP", "SIERA", "xERA", "BB/9", "HR/9")
  expect_setequal(result, starter)
  expect_length(result, 8L)
  expect_equal(result, toupper(result))
  expect_equal(length(result), length(unique(result)))
})

# ---------------------------------------------------------------------------
# TC-INV-3: Accessor is callable without error
# ---------------------------------------------------------------------------

test_that("inverse_categories() is callable without errors", {
  expect_no_error(inverse_categories())
  expect_no_warning(inverse_categories())
})

# ---------------------------------------------------------------------------
# TC-INV-4: K/9 is NOT in the starter list
# ---------------------------------------------------------------------------

test_that("K/9 is not in inverse_categories()", {
  expect_false("K/9" %in% inverse_categories())
})
