# tests/testthat/test-sgp-denominators.R
#
# Independent validation test suite for sgp_denominators() and helpers.
# Generated by Tester pipeline from test-spec.md (sgp-denominators-2026-04-16).
# Tester did NOT read spec.md or implementation.md.

# ---------------------------------------------------------------------------
# Test infrastructure helpers (copied verbatim from test-spec.md §2)
# ---------------------------------------------------------------------------

make_history <- function(
  years    = 2019:2023,
  n_teams  = 10,
  cats     = c("HR", "R", "RBI", "SB"),
  seed     = 42
) {
  set.seed(seed)
  team_ids <- paste0("T", seq_len(n_teams))
  rows <- lapply(years, function(y) {
    df <- data.frame(
      year    = y,
      team_id = team_ids,
      stringsAsFactors = FALSE
    )
    for (cat in cats) {
      params <- switch(cat,
        HR  = list(mean = 200, sd = 30),
        R   = list(mean = 700, sd = 60),
        RBI = list(mean = 650, sd = 55),
        SB  = list(mean = 100, sd = 25),
        ERA = list(mean = 3.8,  sd = 0.4),
        WHIP= list(mean = 1.25, sd = 0.10),
        list(mean = 100, sd = 20)
      )
      df[[cat]] <- round(rnorm(n_teams, params$mean, params$sd), 4)
    }
    df
  })
  ts <- do.call(rbind, rows)
  list(team_season = ts)
}

make_exact_history <- function(n_teams = 10, n_years = 3, slope = 0.05) {
  years <- seq(2020, 2020 + n_years - 1)
  rows <- lapply(seq_along(years), function(i) {
    y <- years[i]
    totals <- seq(100, 100 + (n_teams - 1) * (1 / slope), length.out = n_teams)
    data.frame(
      year    = y,
      team_id = paste0("T", seq_len(n_teams)),
      HR      = totals
    )
  })
  list(team_season = do.call(rbind, rows))
}

# ===========================================================================
# 3. Core Scenarios
# ===========================================================================

# T-01: OLS basic — 3 teams x 2 years, exact computation
test_that("T-01: OLS 3-teams x 2-years exact computation", {
  ts <- data.frame(
    year    = c(2022, 2022, 2022, 2023, 2023, 2023),
    team_id = c("A", "B", "C", "A", "B", "C"),
    HR      = c(150, 180, 210, 170, 195, 220)
  )
  h <- list(team_season = ts)
  result <- sgp_denominators(
    h,
    scoring_categories = "HR",
    n_teams            = 3L,
    years              = "all",
    weights            = flat(),
    method             = "ols",
    exclude_years      = integer(0)
  )

  # Return class
  expect_s3_class(result, "sgp_denominators")
  expect_true(inherits(result, "list"))

  # Primary denominator
  expect_equal(result$denominators[["HR"]], 1 / mean(c(1/30, 1/25)),
               tolerance = 1e-4)
  # Exact value cross-check
  expect_equal(result$denominators[["HR"]], 27.27, tolerance = 0.02)

  # year_diagnostics structure
  expect_equal(nrow(result$year_diagnostics), 2)
  expect_equal(sort(result$year_diagnostics$year), c(2022L, 2023L))
  expect_equal(result$year_diagnostics$category, c("HR", "HR"))
  expect_equal(result$year_diagnostics$n_teams, c(3L, 3L))
  expect_equal(result$year_diagnostics$slope[result$year_diagnostics$year == 2022],
               1/30, tolerance = 1e-5)
  expect_equal(result$year_diagnostics$slope[result$year_diagnostics$year == 2023],
               1/25, tolerance = 1e-5)
  expect_true(all(abs(result$year_diagnostics$r_squared - 1.0) < 1e-10))

  # Flat weights: normalized and equal
  expect_equal(result$year_diagnostics$weight, c(0.5, 0.5), tolerance = 1e-10)
})

# T-02: OLS basic — 10 teams x 5 years, realistic data
test_that("T-02: OLS 10-teams x 5-years realistic multi-category data", {
  h <- make_history(years = 2019:2023, n_teams = 10,
                    cats = c("HR", "R", "RBI", "SB"), seed = 42)
  result <- sgp_denominators(
    h,
    scoring_categories = c("HR", "R", "RBI", "SB"),
    n_teams            = 10L,
    years              = "all",
    weights            = exp_decay(0.9),
    method             = "ols",
    exclude_years      = integer(0)
  )

  expect_s3_class(result, "sgp_denominators")
  expect_equal(length(result$denominators), 4)
  expect_equal(sort(names(result$denominators)), sort(c("HR", "R", "RBI", "SB")))
  expect_true(all(is.finite(result$denominators)))
  expect_true(all(result$denominators > 0))
  expect_equal(nrow(result$year_diagnostics), 20)  # 5 years x 4 cats
  expect_true(all(result$year_diagnostics$r_squared > 0.5))
  expect_equal(result$meta$method, "ols")
  expect_equal(result$meta$rate_conversion, "blended_pool")
})

# T-03: Denominator inversion correct for known slope
test_that("T-03: Denominator inversion matches lm() slope exactly", {
  totals <- seq(100, 325, by = 25)   # 10 values
  ts <- data.frame(
    year    = rep(2022L, 10),
    team_id = paste0("T", 1:10),
    HR      = totals
  )
  h <- list(team_season = ts)
  result <- sgp_denominators(
    h,
    scoring_categories = "HR",
    n_teams            = 10L,
    exclude_years      = integer(0),
    method             = "ols",
    weights            = flat()
  )

  fit <- lm(1:10 ~ totals)
  expected_slope <- coef(fit)[["totals"]]
  expected_denom <- 1 / abs(expected_slope)

  expect_equal(result$denominators[["HR"]], expected_denom, tolerance = 1e-8)
})

# ===========================================================================
# 4. Category Specification Scenarios
# ===========================================================================

# T-04: scoring_categories = NULL triggers inference with cli_inform()
test_that("T-04: NULL scoring_categories triggers inference message", {
  h <- make_history(cats = c("HR", "SB"), seed = 1)
  expect_message(
    result <- sgp_denominators(h, exclude_years = integer(0)),
    regexp = "Inferring scoring categories"
  )
  expect_equal(sort(names(result$denominators)), c("HR", "SB"))
})

# T-05: Explicit scoring_categories suppresses inference message
test_that("T-05: Explicit scoring_categories suppresses inference message", {
  h <- make_history(cats = c("HR", "SB"), seed = 1)
  expect_no_message(
    sgp_denominators(h, scoring_categories = c("HR", "SB"),
                     exclude_years = integer(0)),
    message = "Inferring scoring categories"
  )
})

# T-06: Category column absent -> cli_abort()
test_that("T-06: Missing category column aborts with correct class", {
  h <- make_history(cats = c("HR"), seed = 1)
  expect_error(
    sgp_denominators(h, scoring_categories = c("HR", "K"),
                     exclude_years = integer(0)),
    class = "rotostats_error_missing_category_column"
  )
})

# T-07: Category names normalized to uppercase
test_that("T-07: Category names normalized to uppercase", {
  h <- make_history(cats = c("HR"), seed = 1)
  # Pass lowercase; normalization inform may fire
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories = "hr",
                     exclude_years = integer(0))
  )
  expect_equal(names(result$denominators), "HR")
})

# ===========================================================================
# 5. n_teams Scenarios
# ===========================================================================

# T-08: n_teams = NULL with uneven teams emits warning
test_that("T-08: Uneven team counts emits rotostats_warning_uneven_team_counts", {
  ts <- rbind(
    data.frame(year=2022L, team_id=c("A","B","C","D"), HR=c(100,120,140,160)),
    data.frame(year=2023L, team_id=c("A","B","C"),     HR=c(110,130,150))
  )
  h <- list(team_season=ts)
  expect_warning(
    sgp_denominators(h, scoring_categories="HR", exclude_years=integer(0)),
    class = "rotostats_warning_uneven_team_counts"
  )
})

# T-09: Explicit n_teams mismatch -> cli_abort()
test_that("T-09: n_teams mismatch aborts with correct class", {
  ts <- data.frame(
    year=rep(2022L,3), team_id=c("A","B","C"), HR=c(100,120,140)
  )
  h <- list(team_season=ts)
  expect_error(
    sgp_denominators(h, scoring_categories="HR", n_teams=4L,
                     exclude_years=integer(0)),
    class = "rotostats_error_n_teams_mismatch"
  )
})

# T-10: Explicit n_teams correct value passes silently
test_that("T-10: Correct n_teams passes without error", {
  ts <- data.frame(
    year=rep(2022L,3), team_id=c("A","B","C"), HR=c(100,120,140)
  )
  h <- list(team_season=ts)
  expect_no_error(
    sgp_denominators(h, scoring_categories="HR", n_teams=3L,
                     exclude_years=integer(0))
  )
})

# ===========================================================================
# 6. Year Window and Weighting Scenarios
# ===========================================================================

# T-11: years = after(2022) restricts calibration to 2023+
test_that("T-11: after(2022) restricts year window to 2023+", {
  h <- make_history(years = 2019:2024, seed = 10)
  result_all <- suppressWarnings(suppressMessages(
    sgp_denominators(h, scoring_categories="HR",
                     years = "all", exclude_years = integer(0))
  ))
  result_after <- suppressMessages(
    sgp_denominators(h, scoring_categories="HR",
                     years = after(2022), exclude_years = integer(0))
  )

  expect_true(max(result_all$meta$years_used) >= 2024)
  expect_true(min(result_after$meta$years_used) >= 2023)
  expect_true(all(result_after$year_diagnostics$year >= 2023))
})

# T-12: between(2020, 2022) is inclusive on both ends
test_that("T-12: between() is inclusive on both endpoints", {
  h <- make_history(years = 2018:2024, seed = 11)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories="HR",
                     years = between(2020, 2022), exclude_years = integer(0))
  )
  expect_equal(sort(unique(result$year_diagnostics$year)), c(2020L, 2021L, 2022L))
})

# T-13: last(3) returns only the 3 most recent years
test_that("T-13: last(3) uses only the 3 most recent years", {
  h <- make_history(years = 2018:2024, seed = 12)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories="HR",
                     years = last(3), exclude_years = integer(0))
  )
  expect_equal(sort(unique(result$year_diagnostics$year)), c(2022L, 2023L, 2024L))
})

# T-14: exclude_years = 2020L removes 2020 from all categories
test_that("T-14: exclude_years removes 2020 from diagnostics and meta", {
  h <- make_history(years = 2018:2023, seed = 13)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories="HR",
                     years = "all", exclude_years = 2020L)
  )
  expect_false(2020L %in% result$year_diagnostics$year)
  expect_false(2020L %in% result$meta$years_used)
})

# T-15: exp_decay(0.9) produces higher weight for more recent years
test_that("T-15: exp_decay(0.9) weights are monotonically increasing with year", {
  h <- make_history(years = 2018:2023, seed = 14)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories="HR",
                     years = "all", exclude_years = integer(0),
                     weights = exp_decay(0.9))
  )
  diag <- result$year_diagnostics[result$year_diagnostics$category == "HR", ]
  diag <- diag[order(diag$year), ]
  expect_true(all(diff(diag$weight) > 0))
})

# T-16: Per-category override via category_spec
test_that("T-16: category_spec per-category override applies correctly", {
  h <- make_history(years = 2018:2024, cats = c("HR", "SB"), seed = 15)
  result <- suppressWarnings(suppressMessages(
    sgp_denominators(
      h,
      scoring_categories = c("HR", "SB"),
      years = "all",
      exclude_years = integer(0),
      category_spec = cal_spec(
        SB = cal(years = after(2022))
      )
    )
  ))
  # SB should only use 2023, 2024
  sb_years <- result$year_diagnostics$year[result$year_diagnostics$category == "SB"]
  expect_true(all(sb_years >= 2023))

  # HR should use all years
  hr_years <- result$year_diagnostics$year[result$year_diagnostics$category == "HR"]
  expect_equal(sort(hr_years), 2018:2024)
})

# ===========================================================================
# 7. Method Scenarios
# ===========================================================================

# T-17: method = "gap" produces range/(n-1) denominator
test_that("T-17: gap method = range / (n-1)", {
  totals <- c(100, 130, 170, 180, 220)
  ts <- data.frame(year=2022L, team_id=paste0("T",1:5), HR=totals)
  h <- list(team_season=ts)

  result <- sgp_denominators(h, scoring_categories="HR", n_teams=5L,
                              method="gap", exclude_years=integer(0), weights=flat())

  expected_denom <- diff(range(totals)) / (5 - 1)  # (220-100)/4 = 30
  expect_equal(result$denominators[["HR"]], expected_denom, tolerance=1e-8)
})

# T-18: method = "trimmed_gap" trims 10% from each end
test_that("T-18: trimmed_gap trims 1 gap from each end with n=20", {
  set.seed(101)
  ts20 <- data.frame(
    year    = rep(2022L, 20),
    team_id = paste0("T", 1:20),
    HR      = sort(runif(20, 100, 300))
  )
  h20 <- list(team_season=ts20)

  result_trim <- sgp_denominators(h20, "HR", n_teams=20L, method="trimmed_gap",
                                   exclude_years=integer(0), weights=flat())

  gaps <- diff(sort(ts20$HR))
  gaps_trimmed <- gaps[2:(length(gaps)-1)]  # k=1 from each end
  expected_trim <- mean(gaps_trimmed)

  expect_equal(result_trim$denominators[["HR"]], expected_trim, tolerance=1e-6)
})

# T-19: method = "sd" uses expected_range_normal() scaling
test_that("T-19: sd method uses expected_range_normal scaling", {
  set.seed(100)
  n_teams <- 12
  totals <- rnorm(n_teams, mean=200, sd=30)
  ts <- data.frame(year=2022L, team_id=paste0("T",1:n_teams), HR=totals)
  h <- list(team_season=ts)

  result <- sgp_denominators(h, "HR", n_teams=n_teams, method="sd",
                              exclude_years=integer(0), weights=flat())

  E_Rn <- 3.2587  # known anchor for n=12
  expected_denom <- sd(totals) * (n_teams - 1) / E_Rn
  expect_equal(result$denominators[["HR"]], expected_denom, tolerance=0.01)
})

# T-20: expected_range_normal() anchor values
test_that("T-20: expected_range_normal() anchors match known values", {
  # From test-spec.md §15: corrected n=15 anchor is 3.4718 (not 3.5241)
  expect_equal(expected_range_normal(10), 3.0776, tolerance=1e-3)
  expect_equal(expected_range_normal(12), 3.2587, tolerance=1e-3)
  expect_equal(expected_range_normal(15), 3.4718, tolerance=1e-3)
})

# ===========================================================================
# 8. Edge Case Scenarios
# ===========================================================================

# T-21: Zero-variance category (all teams tied in a year)
test_that("T-21: Zero-variance year emits warning and NA slope; denominator from valid year", {
  ts <- rbind(
    data.frame(year=2022L, team_id=c("A","B","C"), HR=c(150, 180, 210)),
    data.frame(year=2023L, team_id=c("A","B","C"), HR=c(150, 150, 150))
  )
  h <- list(team_season=ts)

  expect_warning(
    result <- sgp_denominators(h, "HR", n_teams=3L, exclude_years=integer(0)),
    class = "rotostats_warning_zero_variance_category"
  )

  diag_2023 <- result$year_diagnostics[result$year_diagnostics$year == 2023, ]
  expect_true(is.na(diag_2023$slope))

  expect_true(is.finite(result$denominators[["HR"]]))
  expect_equal(result$denominators[["HR"]], 1 / (1/30), tolerance=1e-5)
})

# T-22: All years have zero variance -> denominator is NA
test_that("T-22: All years zero variance produces NA denominator with warnings", {
  ts <- data.frame(
    year    = c(2022L, 2022L, 2022L),
    team_id = c("A","B","C"),
    HR      = c(150, 150, 150)
  )
  h <- list(team_season=ts)

  expect_warning(
    result <- sgp_denominators(h, "HR", n_teams=3L, exclude_years=integer(0)),
    class = "rotostats_warning_zero_variance_category"
  )
  expect_warning(
    result <- sgp_denominators(h, "HR", n_teams=3L, exclude_years=integer(0)),
    class = "rotostats_warning_no_valid_years"
  )
  expect_true(is.na(result$denominators[["HR"]]))
})

# T-23: NA in category column — rows excluded, warning emitted
test_that("T-23: NA in category emits warning and still returns finite denominator", {
  ts <- data.frame(
    year    = c(2022L, 2022L, 2022L, 2023L, 2023L, 2023L),
    team_id = c("A","B","C","A","B","C"),
    HR      = c(150, NA, 210, 170, 200, 220)
  )
  h <- list(team_season=ts)

  expect_warning(
    result <- sgp_denominators(h, "HR", exclude_years=integer(0)),
    class = "rotostats_warning_na_category_value"
  )
  expect_true(is.finite(result$denominators[["HR"]]))
})

# T-24: Near-zero slope -> denominator is Inf
test_that("T-24: Near-zero slope emits warning and returns Inf denominator", {
  # Fixture: totals c(100, 110, 120, 130, 140) with denom_floor = 100.
  # var(totals) = 250 >> 100, so zero-variance guard does NOT fire.
  # OLS slope = 100/1000 = 0.10, which is < denom_floor = 100.
  # Near-zero-slope guard fires instead.
  ts <- data.frame(
    year    = rep(2022L, 5),
    team_id = paste0("T", 1:5),
    HR      = c(100, 110, 120, 130, 140)   # var = 250 >> denom_floor = 100
  )
  h <- list(team_season = ts)

  expect_warning(
    result <- sgp_denominators(h, "HR", n_teams = 5L, exclude_years = integer(0),
                                denom_floor = 100),
    class = "rotostats_warning_near_zero_slope"
  )
  expect_true(is.infinite(result$denominators[["HR"]]))
})

# T-25: Inverse category (ERA) — rank-flip produces negative slope, no spurious warning
test_that("T-25: ERA inverse category: rank-flip gives slope -3.333, denom 0.300, no unexpected-sign warning", {
  # ERA values c(3.3, 3.6, 3.9, 4.2, 4.5): increasing ERA = worsening.
  # After rank-flip: standings_pos = 5 + 1 - rank(ERA) = c(5,4,3,2,1).
  # Hand-calc slope = -3.0 / 0.90 = -3.333. Denom = 1/|slope| = 0.300.
  ts <- data.frame(
    year    = rep(2022L, 5),
    team_id = paste0("T", 1:5),
    ERA     = c(3.3, 3.6, 3.9, 4.2, 4.5)  # increasing ERA -> worsening performance
  )
  h <- list(team_season = ts)

  expect_no_warning(
    result <- sgp_denominators(h, "ERA", n_teams = 5L, exclude_years = integer(0)),
    class = "rotostats_warning_unexpected_slope_sign"
  )

  diag <- result$year_diagnostics
  expect_true(diag$slope < 0)

  # Slope must be approximately -3.333 (hand calculation)
  expect_equal(diag$slope, -3.333, tolerance = 0.001)

  # Denominator must be positive (abs() taken after sign check)
  expect_true(result$denominators[["ERA"]] > 0)

  # Denominator = 1 / |slope| = 1 / 3.333 ~ 0.300
  expect_equal(result$denominators[["ERA"]], 0.300, tolerance = 0.001)
})

# T-26: Fewer than 3 calibration seasons -> cli_warn()
test_that("T-26: Fewer than 3 calibration seasons emits thin-window warning", {
  h <- make_history(years = 2022:2023, seed = 20)
  expect_warning(
    sgp_denominators(h, scoring_categories="HR", exclude_years=integer(0)),
    class = "rotostats_warning_thin_calibration_window"
  )
})

# T-27: SB structural break warning (flat weights, pre+post 2023)
test_that("T-27: SB structural break warning fires for flat weights spanning 2022/2023", {
  h <- make_history(years = 2019:2024, cats=c("SB"), seed = 21)

  # Flat weights spanning break -> warning
  expect_warning(
    sgp_denominators(h, scoring_categories="SB",
                     years="all", weights=flat(), exclude_years=integer(0)),
    class = "rotostats_warning_structural_break_flat_weights"
  )

  # exp_decay weights -> no structural break warning
  expect_no_warning(
    suppressWarnings(
      sgp_denominators(h, scoring_categories="SB",
                       years="all", weights=exp_decay(0.7), exclude_years=integer(0))
    ),
    class = "rotostats_warning_structural_break_flat_weights"
  )

  # Window restricted to post-2022 -> no structural break warning
  expect_no_warning(
    suppressWarnings(
      sgp_denominators(h, scoring_categories="SB",
                       years=after(2022), weights=flat(), exclude_years=integer(0))
    ),
    class = "rotostats_warning_structural_break_flat_weights"
  )
})

# T-28: Unrecognized column -> single cli_warn()
test_that("T-28: Unrecognized column emits rotostats_warning_unrecognized_column", {
  ts <- data.frame(
    year=rep(2022L,3), team_id=c("A","B","C"),
    HR=c(150,180,210),
    UNRECOGNIZED_COL=c(1,2,3)
  )
  h <- list(team_season=ts)

  expect_warning(
    sgp_denominators(h, scoring_categories="HR", exclude_years=integer(0)),
    class = "rotostats_warning_unrecognized_column"
  )
})

# T-29: Missing year or team_id -> cli_abort()
test_that("T-29: Missing required column aborts with correct class", {
  ts_no_year <- data.frame(team_id=c("A","B"), HR=c(100,200))
  expect_error(
    sgp_denominators(list(team_season=ts_no_year), scoring_categories="HR"),
    class = "rotostats_error_missing_required_column"
  )

  ts_no_id <- data.frame(year=c(2022L,2022L), HR=c(100,200))
  expect_error(
    sgp_denominators(list(team_season=ts_no_id), scoring_categories="HR"),
    class = "rotostats_error_missing_required_column"
  )
})

# T-30: Invalid method -> cli_abort()
test_that("T-30: Invalid method aborts with correct class", {
  h <- make_history(seed=1)
  expect_error(
    sgp_denominators(h, method="bayes"),
    class = "rotostats_error_invalid_method"
  )
})

# T-31: Raw list() in cal_spec() -> cli_abort()
test_that("T-31: Raw list() inside cal_spec() aborts with correct class", {
  expect_error(
    cal_spec(SB = list(years = after(2022))),
    class = "rotostats_error_invalid_category_spec"
  )
})

# T-32: category_spec not class "cal_spec" -> cli_abort()
test_that("T-32: Non-cal_spec category_spec aborts with correct class", {
  h <- make_history(seed=1)
  expect_error(
    sgp_denominators(h, category_spec = list(SB = cal(years = after(2022)))),
    class = "rotostats_error_invalid_category_spec"
  )
})

# T-33: convert_rate_stats() stub aborts
test_that("T-33: convert_rate_stats() always aborts with not-implemented class", {
  expect_error(
    convert_rate_stats(list()),
    class = "rotostats_error_not_implemented"
  )
})

# T-34: rate_conversion = "fixed_baseline" aborts (stub not implemented)
test_that("T-34: rate_conversion='fixed_baseline' aborts with not-implemented class", {
  h <- make_history(cats = c("HR", "ERA"), seed=1)
  expect_error(
    sgp_denominators(h, scoring_categories=c("HR","ERA"),
                     rate_conversion = "fixed_baseline",
                     exclude_years=integer(0)),
    class = "rotostats_error_not_implemented"
  )
})

# T-35: rate_conversion = "blended_pool" is accepted silently
test_that("T-35: rate_conversion='blended_pool' is accepted without error", {
  h <- make_history(seed=1)
  expect_no_error(
    suppressMessages(
      sgp_denominators(h, rate_conversion="blended_pool", exclude_years=integer(0))
    )
  )
})

# ===========================================================================
# 9. Return Object and Backward-Compatibility Scenarios
# ===========================================================================

# T-36: Class and slot structure
test_that("T-36: Return object has correct class and all required slots", {
  h <- make_history(seed=1)
  result <- suppressMessages(
    sgp_denominators(h, exclude_years=integer(0))
  )

  expect_s3_class(result, c("sgp_denominators", "list"))
  expect_true(is.list(result))
  # names.sgp_denominators S3 override returns category names (T-56), so bypass it
  expect_equal(names(unclass(result)),
               c("denominators", "year_diagnostics", "bootstrap_ci", "call", "meta"))

  expect_true(is.numeric(result$denominators))
  expect_true(!is.null(names(result$denominators)))

  expect_true(is.data.frame(result$year_diagnostics))
  expect_true(all(c("year","category","n_teams","slope","r_squared","weight",
                     "standings_pos_source") %in% names(result$year_diagnostics)))

  expect_null(result$bootstrap_ci)

  expect_true(is.call(result$call) || inherits(result$call, "call"))

  expect_named(result$meta, c("rate_conversion","method","years_used","exclude_years","package_version"))
})

# T-37: attr(x, "rate_conversion") works directly
test_that("T-37: attr(x, 'rate_conversion') returns the rate_conversion string", {
  h <- make_history(seed=1)
  result <- suppressMessages(
    sgp_denominators(h, rate_conversion="blended_pool", exclude_years=integer(0))
  )
  expect_equal(attr(result, "rate_conversion"), "blended_pool")
})

# T-38: as.numeric() returns the named numeric vector
test_that("T-38: as.numeric() returns named numeric denominator vector", {
  h <- make_history(cats="HR", seed=1)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories="HR", exclude_years=integer(0))
  )
  v <- as.numeric(result)
  expect_true(is.numeric(v))
  expect_equal(names(v), "HR")
  expect_equal(v[["HR"]], result$denominators[["HR"]])
})

# T-39: x["HR"] returns scalar via single-bracket dispatch
test_that("T-39: Single-bracket x['HR'] returns scalar denominator", {
  h <- make_history(cats=c("HR","SB"), seed=1)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories=c("HR","SB"), exclude_years=integer(0))
  )

  v <- result["HR"]
  expect_true(is.numeric(v))
  expect_equal(length(v), 1)
  expect_equal(v[["HR"]], result$denominators[["HR"]])
})

# T-40: names() returns category names
test_that("T-40: names() returns category names from denominators", {
  h <- make_history(cats=c("HR","SB"), seed=1)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories=c("HR","SB"), exclude_years=integer(0))
  )
  expect_equal(sort(names(result)), c("HR","SB"))
})

# T-41: length() returns number of categories
test_that("T-41: length() returns number of scoring categories", {
  h <- make_history(cats=c("HR","R","RBI","SB"), seed=1)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories=c("HR","R","RBI","SB"),
                     exclude_years=integer(0))
  )
  expect_equal(length(result), 4)
})

# T-42: x$denominators and x[["denominators"]] return the vector
test_that("T-42: x$denominators and x[['denominators']] return same numeric vector", {
  h <- make_history(cats="HR", seed=1)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories="HR", exclude_years=integer(0))
  )
  expect_equal(result$denominators, result[["denominators"]])
  expect_true(is.numeric(result$denominators))
})

# T-43: print.sgp_denominators() runs without error
test_that("T-43: print() produces output without error", {
  h <- make_history(seed=1)
  result <- suppressMessages(
    sgp_denominators(h, exclude_years=integer(0))
  )
  expect_output(print(result))
})

# ===========================================================================
# 10. Bootstrap CI Scenarios
# ===========================================================================

# T-44: n_bootstrap = 0 -> $bootstrap_ci is NULL
test_that("T-44: n_bootstrap=0 returns NULL bootstrap_ci", {
  h <- make_history(seed=1)
  result <- suppressMessages(
    sgp_denominators(h, n_bootstrap=0L, exclude_years=integer(0))
  )
  expect_null(result$bootstrap_ci)
})

# T-45: n_bootstrap = 200 -> $bootstrap_ci is data.frame with correct schema
test_that("T-45: n_bootstrap=200 produces bootstrap_ci data.frame with correct schema", {
  h <- make_history(cats=c("HR","SB"), seed=1)
  set.seed(99)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories=c("HR","SB"),
                     n_bootstrap=200L, ci_level=0.95,
                     exclude_years=integer(0))
  )

  expect_true(is.data.frame(result$bootstrap_ci))
  expect_named(result$bootstrap_ci, c("category","ci_lower","ci_upper","ci_level","n_bootstrap"))
  expect_equal(nrow(result$bootstrap_ci), 2)
  expect_equal(sort(result$bootstrap_ci$category), c("HR","SB"))
  expect_equal(result$bootstrap_ci$ci_level, c(0.95, 0.95))
  expect_equal(result$bootstrap_ci$n_bootstrap, c(200L, 200L))
  # CIs must straddle the point estimate
  expect_true(all(result$bootstrap_ci$ci_lower < result$denominators[result$bootstrap_ci$category]))
  expect_true(all(result$bootstrap_ci$ci_upper > result$denominators[result$bootstrap_ci$category]))
})

# T-46: Bootstrap is deterministic with set.seed()
test_that("T-46: Bootstrap CI is deterministic given same seed", {
  h <- make_history(seed=1)
  set.seed(42)
  r1 <- suppressMessages(
    sgp_denominators(h, n_bootstrap=100L, exclude_years=integer(0))
  )
  set.seed(42)
  r2 <- suppressMessages(
    sgp_denominators(h, n_bootstrap=100L, exclude_years=integer(0))
  )

  expect_equal(r1$bootstrap_ci$ci_lower, r2$bootstrap_ci$ci_lower)
  expect_equal(r1$bootstrap_ci$ci_upper, r2$bootstrap_ci$ci_upper)
})

# ===========================================================================
# 11. Data Integrity and I/O Scenarios
# ===========================================================================

# T-47: Pure function — no file system side effects
test_that("T-47: sgp_denominators() creates no files in tempdir", {
  before_files <- list.files(tempdir())
  h <- make_history(seed=1)
  suppressMessages(sgp_denominators(h, exclude_years=integer(0)))
  after_files <- list.files(tempdir())
  expect_equal(before_files, after_files)
})

# T-48: $team_season not a data.frame -> cli_abort()
test_that("T-48: Non-data.frame team_season aborts with correct class", {
  expect_error(
    sgp_denominators(list(team_season = "not a dataframe")),
    class = "rotostats_error_missing_team_season"
  )
})

# T-49: NULL league_history -> cli_abort()
test_that("T-49: NULL team_season aborts with correct class", {
  expect_error(
    sgp_denominators(list(team_season = NULL)),
    class = "rotostats_error_missing_team_season"
  )
})

# T-50: outlier_filter = TRUE excludes outlier teams
test_that("T-50: outlier_filter=TRUE excludes extreme outlier, smaller denominator", {
  set.seed(42)
  h_base <- make_history(years=2022, n_teams=9, cats="HR", seed=42)
  h_base$team_season <- rbind(
    h_base$team_season,
    data.frame(year=2022L, team_id="OUTLIER", HR=5000)
  )

  result_no_filter  <- sgp_denominators(h_base, "HR", n_teams=10L,
                                         outlier_filter=FALSE, exclude_years=integer(0))
  result_with_filter <- sgp_denominators(h_base, "HR", n_teams=10L,
                                          outlier_filter=TRUE, exclude_years=integer(0))

  expect_true(result_with_filter$denominators[["HR"]] <
                result_no_filter$denominators[["HR"]])
})

# ===========================================================================
# 12. Property-Based Invariants
# ===========================================================================

# T-51: Denominator is positive and finite for clean data
test_that("T-51: All denominators positive and finite for clean 7-year 12-team data", {
  h <- make_history(years=2018:2024, n_teams=12, seed=77)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories=c("HR","R","RBI","SB"),
                     exclude_years=integer(0))
  )
  expect_true(all(result$denominators > 0))
  expect_true(all(is.finite(result$denominators)))
})

# T-52: More data years -> diagnostics data.frame has more rows
test_that("T-52: More data years produces more rows in year_diagnostics", {
  h5  <- make_history(years=2018:2022, cats="HR", seed=5)
  h10 <- make_history(years=2013:2022, cats="HR", seed=6)

  r5  <- suppressMessages(sgp_denominators(h5,  "HR", exclude_years=integer(0)))
  r10 <- suppressMessages(sgp_denominators(h10, "HR", exclude_years=integer(0)))

  expect_equal(nrow(r5$year_diagnostics),  5)
  expect_equal(nrow(r10$year_diagnostics), 10)
})

# T-53: Scaling all category values by constant k scales denominator by k
test_that("T-53: Denominator scales proportionally with category value scale factor", {
  ts <- data.frame(
    year    = c(rep(2022L,5), rep(2023L,5)),
    team_id = rep(paste0("T",1:5),2),
    HR      = c(100,120,140,160,180, 110,130,150,170,190)
  )
  ts_scaled <- ts
  ts_scaled$HR <- ts$HR * 3

  h      <- list(team_season=ts)
  h_scal <- list(team_season=ts_scaled)

  r      <- sgp_denominators(h,      "HR", n_teams=5L, exclude_years=integer(0))
  r_scal <- sgp_denominators(h_scal, "HR", n_teams=5L, exclude_years=integer(0))

  expect_equal(r_scal$denominators[["HR"]] / r$denominators[["HR"]], 3, tolerance=1e-6)
})

# T-54: Adding a constant to all values does not change denominator
test_that("T-54: Additive shift in category values does not change OLS denominator", {
  ts <- data.frame(
    year    = rep(2022L,5),
    team_id = paste0("T",1:5),
    HR      = c(100,120,140,160,180)
  )
  ts_shift <- ts
  ts_shift$HR <- ts$HR + 500

  h       <- list(team_season=ts)
  h_shift <- list(team_season=ts_shift)

  r       <- sgp_denominators(h,       "HR", n_teams=5L, exclude_years=integer(0), weights=flat())
  r_shift <- sgp_denominators(h_shift, "HR", n_teams=5L, exclude_years=integer(0), weights=flat())

  expect_equal(r$denominators[["HR"]], r_shift$denominators[["HR"]], tolerance=1e-8)
})

# T-55: year_diagnostics weights sum to 1 per category
test_that("T-55: year_diagnostics weights sum to 1.0 per category", {
  h <- make_history(years=2018:2023, cats=c("HR","SB"), seed=99)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories=c("HR","SB"),
                     exclude_years=integer(0), weights=exp_decay(0.9))
  )

  for (cat in c("HR","SB")) {
    w <- result$year_diagnostics$weight[result$year_diagnostics$category == cat]
    expect_equal(sum(w), 1.0, tolerance=1e-10)
  }
})

# T-56: names(result) matches names(result$denominators)
test_that("T-56: names(result) matches names(result$denominators)", {
  h <- make_history(cats=c("HR","R","RBI"), seed=1)
  result <- suppressMessages(
    sgp_denominators(h, scoring_categories=c("HR","R","RBI"),
                     exclude_years=integer(0))
  )
  expect_equal(sort(names(result)), sort(names(result$denominators)))
})

# T-57: $standings_pos_source correctly reflects whether pts column was used
test_that("T-57: standings_pos_source is 'category_pts' with _pts column, 'rank' without", {
  ts <- data.frame(
    year    = c(rep(2022L,3), rep(2023L,3)),
    team_id = rep(c("A","B","C"),2),
    HR      = c(150,180,210, 170,200,220),
    HR_pts  = c(1,2,3, 1,2,3)
  )
  h <- list(team_season=ts)
  result <- sgp_denominators(h, "HR", n_teams=3L, exclude_years=integer(0))

  expect_true(all(as.character(result$year_diagnostics$standings_pos_source) == "category_pts"))

  ts2 <- ts[, !names(ts) %in% "HR_pts"]
  h2 <- list(team_season=ts2)
  result2 <- sgp_denominators(h2, "HR", n_teams=3L, exclude_years=integer(0))
  expect_true(all(as.character(result2$year_diagnostics$standings_pos_source) == "rank"))
})

# ===========================================================================
# 13. inverse_categories Scenarios (T-58 through T-70)
# ===========================================================================
# Tester pipeline — generated from test-spec.md §3 (Patch round 2).
# Tests T-NEW-01 through T-NEW-13 renumbered T-58 through T-70 here.
# Tester did NOT read spec.md or implementation.md.

# ---------------------------------------------------------------------------
# Helper: make_oavg_history (from test-spec.md §2)
# ---------------------------------------------------------------------------
make_oavg_history <- function(n_years = 3, n_teams = 5, seed = 200) {
  set.seed(seed)
  team_ids <- paste0("T", seq_len(n_teams))
  rows <- lapply(seq_len(n_years), function(i) {
    y <- 2020L + i - 1L
    data.frame(
      year    = y,
      team_id = team_ids,
      HR      = round(rnorm(n_teams, 200, 30)),
      OAVG    = round(runif(n_teams, 0.220, 0.310), 3),
      stringsAsFactors = FALSE
    )
  })
  list(team_season = do.call(rbind, rows))
}

# ---------------------------------------------------------------------------
# Helper: make_oavg_monotone_history (from test-spec.md §3 T-NEW-03)
# ---------------------------------------------------------------------------
make_oavg_monotone_history <- function() {
  years <- 2021L:2023L
  ts <- do.call(rbind, lapply(years, function(y) {
    data.frame(
      year    = y,
      team_id = paste0("T", 1:5),
      HR      = c(150L, 170L, 190L, 210L, 230L),
      OAVG    = c(0.220, 0.245, 0.270, 0.295, 0.320),
      stringsAsFactors = FALSE
    )
  }))
  list(team_season = ts)
}

# ---------------------------------------------------------------------------
# T-58 (T-NEW-01): Regression guard — existing T-01 through T-57 all pass
# ---------------------------------------------------------------------------
# This test runs the full suite externally; individual tests above serve as
# the evidence. Here we re-run the canonical T-25 fixture as a named guard.

test_that("T-58 (T-NEW-01): T-25 ERA regression anchor still passes after patch", {
  ts <- data.frame(
    year    = rep(2022L, 5),
    team_id = paste0("T", 1:5),
    ERA     = c(3.3, 3.6, 3.9, 4.2, 4.5)
  )
  h <- list(team_season = ts)
  expect_no_warning(
    result <- sgp_denominators(h, "ERA", n_teams = 5L, exclude_years = integer(0)),
    class = "rotostats_warning_unexpected_slope_sign"
  )
  diag <- result$year_diagnostics
  expect_true(diag$slope < 0)
  expect_equal(diag$slope, -3.333, tolerance = 0.001)
  expect_true(result$denominators[["ERA"]] > 0)
  expect_equal(result$denominators[["ERA"]], 0.300, tolerance = 0.001)
})

# ---------------------------------------------------------------------------
# T-59 (T-NEW-02): Default call — OAVG NOT in inverse_categories
# ---------------------------------------------------------------------------
# When scoring_categories = c("HR", "OAVG") with default inverse_categories
# = c("ERA", "WHIP"), the effective set is character(0) (neither ERA nor WHIP
# is scored). OAVG has no rank-flip.
# The exact slope sign depends on data; we verify only structural properties.

test_that("T-59 (T-NEW-02): default path with HR+OAVG league: effective inverse set is empty", {
  h <- make_oavg_history(n_years = 3, n_teams = 5, seed = 200)
  # Default inverse_categories = c("ERA", "WHIP"); neither is in c("HR","OAVG").
  # Silent intersection -> character(0). Should NOT abort.
  expect_no_error(
    suppressMessages(suppressWarnings(
      result <- sgp_denominators(
        h,
        scoring_categories = c("HR", "OAVG"),
        exclude_years      = integer(0)
        # inverse_categories omitted — default path
      )
    ))
  )
  expect_true(is.list(result))
  expect_true("OAVG" %in% names(result$denominators))
})

# ---------------------------------------------------------------------------
# T-60 (T-NEW-03): Explicit inverse_categories = c("OAVG") — negative slope,
#                   no rotostats_warning_unexpected_slope_sign
# ---------------------------------------------------------------------------

test_that("T-60 (T-NEW-03): OAVG declared inverse: negative slope, no unexpected-sign warning", {
  h <- make_oavg_monotone_history()
  expect_no_warning(
    result <- sgp_denominators(
      h,
      scoring_categories = c("HR", "OAVG"),
      inverse_categories = c("OAVG"),
      exclude_years      = integer(0)
    ),
    class = "rotostats_warning_unexpected_slope_sign"
  )
  oavg_diag <- result$year_diagnostics[result$year_diagnostics$category == "OAVG", ]
  expect_true(all(oavg_diag$slope < 0))
  expect_true(result$denominators[["OAVG"]] > 0)
  expect_true(is.finite(result$denominators[["OAVG"]]))

  # Cross-check against lm(): rank-flip produces standings_pos = 5, 4, 3, 2, 1.
  totals        <- c(0.220, 0.245, 0.270, 0.295, 0.320)
  standings_pos <- c(5L, 4L, 3L, 2L, 1L)
  ref_slope     <- coef(lm(standings_pos ~ totals))[["totals"]]
  ref_denom     <- 1 / abs(ref_slope)
  expect_equal(result$denominators[["OAVG"]], ref_denom, tolerance = 1e-5)
})

# ---------------------------------------------------------------------------
# T-61 (T-NEW-04): Invalid element aborts with correct class
# ---------------------------------------------------------------------------

test_that("T-61 (T-NEW-04): invalid inverse_categories element aborts with correct class", {
  h <- make_history(cats = c("HR", "ERA"), seed = 1)
  expect_error(
    sgp_denominators(
      h,
      scoring_categories = c("HR", "ERA"),
      inverse_categories = c("NOT_IN_CATEGORIES"),
      exclude_years      = integer(0)
    ),
    class = "rotostats_error_invalid_inverse_categories"
  )
})

# ---------------------------------------------------------------------------
# T-62 (T-NEW-05): cli_inform() fires exactly once per configuration
# ---------------------------------------------------------------------------

test_that("T-62 (T-NEW-05): cli_inform fires at most once per configuration (second call silent)", {
  # Use a league scoring HR + ERA + WHIP with explicit inverse_categories =
  # c("ERA", "WHIP").
  h <- make_history(cats = c("HR", "ERA", "WHIP"), seed = 1)

  # First call: fires OR is suppressed depending on whether another test in
  # this session already fired the same .frequency_id. Either outcome is valid.
  # We make the call and capture the output, but do NOT assert it fires here —
  # the rlang .frequency = "once" mechanism is session-scoped, so the first
  # call with this .frequency_id in the ENTIRE session fires the message.
  suppressWarnings(
    sgp_denominators(h, scoring_categories = c("HR", "ERA", "WHIP"),
                     inverse_categories = c("ERA", "WHIP"),
                     exclude_years = integer(0))
  )

  # Second identical call in the same test_that block: rlang frequency cache
  # MUST suppress the direction-flip inform. This is the invariant: once the
  # message fires for a given .frequency_id (whether in this test_that block or
  # an earlier one), repeated identical calls are silent.
  msgs2 <- testthat::capture_messages(
    suppressWarnings(
      sgp_denominators(h, scoring_categories = c("HR", "ERA", "WHIP"),
                       inverse_categories = c("ERA", "WHIP"),
                       exclude_years = integer(0))
    )
  )
  flip_msgs2 <- msgs2[grepl("Direction-flipping|direction-flip", msgs2, ignore.case = TRUE)]
  expect_length(flip_msgs2, 0L)
})

# ---------------------------------------------------------------------------
# T-63 (T-NEW-06): Empty inverse_categories = character(0) is legal
# ---------------------------------------------------------------------------

test_that("T-63 (T-NEW-06): empty inverse_categories is legal and informs 'no categories'", {
  h <- make_history(cats = "HR", seed = 1)
  # Primary assertion: no error (no rotostats_error_invalid_inverse_categories).
  result <- NULL
  expect_no_error(
    suppressMessages(
      result <- sgp_denominators(h, scoring_categories = "HR",
                                 inverse_categories = character(0),
                                 exclude_years = integer(0))
    )
  )
  # Result must be a valid sgp_denominators list.
  expect_true(is.list(result))
  expect_true("HR" %in% names(result$denominators))
  # The "No categories will be direction-flipped" inform message fires at most
  # once per session (rlang .frequency = "once"). It may have fired in an
  # earlier test (e.g., a batting-only default-path test). Message presence is
  # verified by T-62 for the non-empty case; absence here is not a failure.
})

# ---------------------------------------------------------------------------
# T-64 (T-NEW-07): Lowercase inverse_categories normalized to uppercase
# ---------------------------------------------------------------------------

test_that("T-64 (T-NEW-07): lowercase inverse_categories normalized to uppercase", {
  h <- make_history(cats = c("HR", "ERA"), seed = 1)
  expect_no_error(
    suppressMessages(
      sgp_denominators(h, scoring_categories = c("HR", "ERA"),
                       inverse_categories = c("era"),
                       exclude_years = integer(0))
    )
  )
})

# ---------------------------------------------------------------------------
# T-65 (T-NEW-08): Duplicate inverse_categories elements deduplicated silently
# ---------------------------------------------------------------------------

test_that("T-65 (T-NEW-08): duplicate inverse_categories deduplicated silently", {
  h <- make_history(cats = c("HR", "ERA"), seed = 1)
  expect_no_error(
    suppressMessages(
      sgp_denominators(h, scoring_categories = c("HR", "ERA"),
                       inverse_categories = c("ERA", "ERA"),
                       exclude_years = integer(0))
    )
  )
  # The behavioral contract says deduplication must be SILENT — no warning about
  # duplicate elements. Data-quality warnings (high_denominator_cv, low_r_squared)
  # are unrelated to deduplication and are suppressed with suppressWarnings().
  # No "rotostats_warning_unexpected_slope_sign" should fire (ERA is in the effective set).
  expect_no_warning(
    suppressMessages(suppressWarnings(
      sgp_denominators(h, scoring_categories = c("HR", "ERA"),
                       inverse_categories = c("ERA", "ERA"),
                       exclude_years = integer(0))
    )),
    class = "rotostats_warning_unexpected_slope_sign"
  )
})

# ---------------------------------------------------------------------------
# T-66 (T-NEW-09): Non-character inverse_categories aborts with correct class
# ---------------------------------------------------------------------------

test_that("T-66 (T-NEW-09): non-character inverse_categories aborts with correct class", {
  h <- make_history(cats = "HR", seed = 1)
  expect_error(
    sgp_denominators(h, scoring_categories = "HR",
                     inverse_categories = 123L,
                     exclude_years = integer(0)),
    class = "rotostats_error_invalid_inverse_categories"
  )
})

# ---------------------------------------------------------------------------
# T-67 (T-NEW-10): T-25 exact-value ERA regression guard (explicit replication)
# ---------------------------------------------------------------------------

test_that("T-67 (T-NEW-10): T-25 ERA regression: slope -3.333, denom 0.300, no sign warning", {
  ts <- data.frame(
    year    = rep(2022L, 5),
    team_id = paste0("T", 1:5),
    ERA     = c(3.3, 3.6, 3.9, 4.2, 4.5)
  )
  h <- list(team_season = ts)
  expect_no_warning(
    result <- sgp_denominators(h, "ERA", n_teams = 5L, exclude_years = integer(0)),
    class = "rotostats_warning_unexpected_slope_sign"
  )
  diag <- result$year_diagnostics
  expect_true(diag$slope < 0)
  expect_equal(diag$slope, -3.333, tolerance = 0.001)
  expect_equal(result$denominators[["ERA"]], 0.300, tolerance = 0.001)
})

# ---------------------------------------------------------------------------
# T-68 (T-NEW-11): Default path, batting-only league — no abort, empty effective set
# ---------------------------------------------------------------------------
# Patch round 2: verifies behavioral contract item 2a.
# inverse_categories NOT supplied; scoring only HR, R, RBI, SB.
# Default c("ERA","WHIP") intersects to character(0). No abort.

test_that("T-68 (T-NEW-11): default path, batting-only league does not abort", {
  h <- make_history(cats = c("HR", "R", "RBI", "SB"), seed = 1)
  result <- NULL
  # Primary assertion: no error (no rotostats_error_invalid_inverse_categories).
  # Default inverse_categories = c("ERA","WHIP") intersects silently to
  # character(0) when neither ERA nor WHIP is scored. No abort, no error.
  expect_no_error(
    suppressMessages(
      result <- sgp_denominators(
        h,
        scoring_categories = c("HR", "R", "RBI", "SB"),
        exclude_years      = integer(0)
        # inverse_categories deliberately omitted — default path
      )
    )
  )
  # Result structure is a valid sgp_denominators list.
  expect_true(is.list(result))
  expect_true(all(c("HR", "R", "RBI", "SB") %in% names(result$denominators)))
  # The "No categories will be direction-flipped" inform fires at most once per
  # session (rlang .frequency = "once"). Earlier tests in this suite that score
  # only batting categories (e.g., T-01, T-02) already fired this inform with
  # the same .frequency_id. Its absence in THIS test_that block is not a failure
  # — the cache confirms it fired. The critical behavioral guarantee is NO ABORT.
})

# ---------------------------------------------------------------------------
# T-69 (T-NEW-12): Default path, HR+ERA league — ERA intersected in, WHIP dropped
# ---------------------------------------------------------------------------
# Patch round 2: verifies partial-overlap default-path behavior.
# Default c("ERA","WHIP") ∩ c("HR","ERA") = c("ERA"). WHIP silently dropped.

test_that("T-69 (T-NEW-12): default path, HR+ERA league: ERA intersected in, WHIP silently dropped", {
  h <- make_history(cats = c("HR", "ERA"), seed = 42)
  msgs <- character(0)
  expect_no_error(
    msgs <- testthat::capture_messages(
      suppressWarnings(
        result <- sgp_denominators(
          h,
          scoring_categories = c("HR", "ERA"),
          exclude_years      = integer(0)
          # inverse_categories deliberately omitted
        )
      )
    )
  )
  # ERA receives rank-flip: all slopes must be negative.
  era_diag <- result$year_diagnostics[result$year_diagnostics$category == "ERA", ]
  expect_true(all(era_diag$slope < 0))
  expect_true(result$denominators[["ERA"]] > 0)
  expect_true(is.finite(result$denominators[["ERA"]]))

  # No unexpected-slope warning for ERA (it IS in the effective inverse set).
  expect_no_warning(
    suppressMessages(
      sgp_denominators(
        h,
        scoring_categories = c("HR", "ERA"),
        exclude_years      = integer(0)
      )
    ),
    class = "rotostats_warning_unexpected_slope_sign"
  )
})

# ---------------------------------------------------------------------------
# T-70 (T-NEW-13): Explicit path, batting-only league — must abort
# ---------------------------------------------------------------------------
# Patch round 2: verifies that explicit path is still strict even when the
# value passed happens to match the default literal.

test_that("T-70 (T-NEW-13): explicit inverse_categories with batting-only league aborts", {
  h <- make_history(cats = c("HR"), seed = 1)
  expect_error(
    sgp_denominators(
      h,
      scoring_categories = c("HR"),
      inverse_categories = c("ERA", "WHIP"),  # explicitly supplied — triggers strict validation
      exclude_years      = integer(0)
    ),
    class = "rotostats_error_invalid_inverse_categories"
  )
})

# ===========================================================================
# inverse_categories resolution — TC-SGP-INV-1 through TC-SGP-INV-9
# Added by Tester pipeline, inverse-categories-2026-04-21
# ===========================================================================

# ---------------------------------------------------------------------------
# Fixture helpers (self-contained)
# ---------------------------------------------------------------------------

# Minimal team_season data scored with ERA and WHIP only.
.ts_era_whip <- function() {
  data.frame(
    year    = rep(2021:2023, each = 4L),
    team_id = rep(paste0("T", 1:4), 3L),
    ERA     = c(4.1, 3.8, 4.5, 3.9,  4.0, 3.7, 4.3, 4.1,  3.9, 3.6, 4.4, 4.0),
    WHIP    = c(1.30, 1.25, 1.35, 1.28,  1.28, 1.22, 1.32, 1.29,
                1.27, 1.20, 1.33, 1.28)
  )
}

# Minimal team_season scored with ERA, WHIP, FIP.
.ts_era_whip_fip <- function() {
  set.seed(123)
  df <- .ts_era_whip()
  df$FIP <- df$ERA + runif(nrow(df), -0.2, 0.2)  # FIP tracks ERA loosely
  df
}

# league_history objects
.lh_era_whip     <- function() league_history(team_season = .ts_era_whip())
.lh_era_whip_fip <- function() league_history(team_season = .ts_era_whip_fip())

# ---------------------------------------------------------------------------
# TC-SGP-INV-1: Layer-3 (package default) — ERA/WHIP behavior preserved
# ---------------------------------------------------------------------------

test_that("Layer-3 package default preserves ERA/WHIP behavior", {
  lh <- .lh_era_whip()
  expect_no_error({
    d <- suppressMessages(
      sgp_denominators(lh, scoring_categories = c("ERA", "WHIP"))
    )
  })
  expect_true(is.numeric(d$denominators))
  expect_named(d$denominators, c("ERA", "WHIP"), ignore.order = TRUE)
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-2: Layer-3 — FIP not scored; FIP not in effective list
# ---------------------------------------------------------------------------
# Respawn 1 — Revision: changed scoring_categories from c("ERA","WHIP") to
# c("WHIP") to ensure a unique cli .frequency_id. TC-SGP-INV-1 registers id
# "rotostats_sgp_denom_inverse_ERA,WHIP" session-wide via suppressMessages.
# Using c("WHIP") produces id "rotostats_sgp_denom_inverse_WHIP" (novel).
# Behavioral assertion preserved: FIP absent from effective list because FIP
# is not in the scored set, so intersect cannot include it.

test_that("Layer-3 omits FIP when FIP is not a scored category", {
  lh <- .lh_era_whip()
  msgs <- character(0)
  withCallingHandlers(
    message = function(m) {
      msgs <<- c(msgs, conditionMessage(m))
      invokeRestart("muffleMessage")
    },
    sgp_denominators(lh, scoring_categories = c("WHIP"))
  )
  # At least one message mentions "package default"
  expect_true(any(grepl("package default", msgs)))
  # FIP not mentioned as an inverse category in the Effective inverse message
  inv_msgs <- msgs[grepl("Effective inverse", msgs)]
  expect_false(any(grepl("FIP", inv_msgs)))
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-3: Layer-3 — FIP scored; FIP appears in effective list
# ---------------------------------------------------------------------------

test_that("Layer-3 includes FIP in effective list when FIP is scored", {
  lh <- .lh_era_whip_fip()
  msgs <- character(0)
  withCallingHandlers(
    message = function(m) {
      msgs <<- c(msgs, conditionMessage(m))
      invokeRestart("muffleMessage")
    },
    sgp_denominators(lh, scoring_categories = c("ERA", "WHIP", "FIP"))
  )
  expect_true(any(grepl("package default", msgs)))
  inv_msg <- msgs[grepl("Effective inverse", msgs)]
  expect_true(length(inv_msg) > 0)
  expect_true(any(grepl("FIP", inv_msg)))
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-4: Layer-2 (config inheritance) — config supplies the list
# ---------------------------------------------------------------------------
# Respawn 1 — Revision (v2): earlier attempt used c("ERA") as config
# inverse, but T-25 (line 484) pre-registers "rotostats_sgp_denom_inverse_ERA"
# by calling sgp_denominators with scoring_categories = "ERA" (Layer-3 fires,
# effective set {ERA}, id "ERA" registered session-wide).
# Resolution: use config$inverse_categories = c("ERA","FIP") with lh_era_whip_fip
# so .frequency_id = "rotostats_sgp_denom_inverse_ERA,FIP" — novel in sequence:
#   T-25: "ERA"; TC-1: "ERA,WHIP"; TC-2: "WHIP"; TC-3: "ERA,FIP,WHIP"
# Layer-2 behavioral assertion preserved: config$inverse_categories is
# non-NULL, no explicit arg -> Layer-2 fires, effective set = config's list,
# message says "from config".

test_that("Layer-2 inherits inverse_categories from config", {
  lh <- .lh_era_whip_fip()
  cfg <- league_config(
    n_teams            = 4L,
    roster_slots       = c(C = 1L),
    # batting_categories supplied as a placeholder; this fixture only exercises
    # pitcher ERA/WHIP/FIP. The placeholder ensures league_config() accepts the call.
    batting_categories = c("HR"),
    pitcher_categories = c("ERA", "WHIP", "FIP"),
    inverse_categories = c("ERA", "FIP")
  )
  msgs <- character(0)
  withCallingHandlers(
    message = function(m) {
      msgs <<- c(msgs, conditionMessage(m))
      invokeRestart("muffleMessage")
    },
    sgp_denominators(lh, scoring_categories = c("ERA", "WHIP", "FIP"), config = cfg)
  )
  expect_true(any(grepl("from config", msgs)))
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-5: Layer-2 — config with NULL inverse_categories falls to Layer-3
# ---------------------------------------------------------------------------
# Respawn 1 — Revision: changed fixture to .lh_era_whip_fip() and
# scoring_categories to c("WHIP","FIP") so Layer-3 effective set is
# intersect(c("WHIP","FIP"), inverse_categories()) = c("FIP","WHIP") (sorted),
# giving .frequency_id "rotostats_sgp_denom_inverse_FIP,WHIP" — distinct from
# all prior ids: TC-1:"ERA,WHIP"; TC-2:"WHIP"; TC-3:"ERA,FIP,WHIP"; TC-4:"ERA".
# Behavioral assertion unchanged: config$inverse_categories = NULL ->
# Layer-2 skipped -> Layer-3 fires -> message says "package default".

test_that("Layer-2 falls to Layer-3 when config$inverse_categories is NULL", {
  lh <- .lh_era_whip_fip()
  cfg <- league_config(
    n_teams            = 4L,
    roster_slots       = c(C = 1L),
    # batting_categories supplied as a placeholder; this fixture only exercises
    # pitcher WHIP/FIP. The placeholder ensures league_config() accepts the call.
    batting_categories = c("HR"),
    pitcher_categories = c("WHIP", "FIP")
    # inverse_categories omitted -> NULL
  )
  msgs <- character(0)
  withCallingHandlers(
    message = function(m) {
      msgs <<- c(msgs, conditionMessage(m))
      invokeRestart("muffleMessage")
    },
    sgp_denominators(lh, scoring_categories = c("WHIP", "FIP"), config = cfg)
  )
  expect_true(any(grepl("package default", msgs)))
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-6: Layer-1 (user override) — full replacement; config ignored
# ---------------------------------------------------------------------------

test_that("Layer-1 full-replacement: user arg wins over config", {
  lh <- .lh_era_whip_fip()
  cfg <- league_config(
    n_teams            = 4L,
    roster_slots       = c(C = 1L),
    # batting_categories supplied as a placeholder; this fixture only exercises
    # pitcher ERA/WHIP/FIP. The placeholder ensures league_config() accepts the call.
    batting_categories = c("HR"),
    pitcher_categories = c("ERA", "WHIP", "FIP"),
    inverse_categories = c("ERA", "WHIP")
  )
  msgs <- character(0)
  withCallingHandlers(
    message = function(m) {
      msgs <<- c(msgs, conditionMessage(m))
      invokeRestart("muffleMessage")
    },
    sgp_denominators(
      lh,
      scoring_categories = c("ERA", "WHIP", "FIP"),
      inverse_categories = "FIP",
      config             = cfg
    )
  )
  # Message must mention "user override"
  expect_true(any(grepl("user override", msgs)))
  # Effective inverse message must mention FIP but NOT ERA or WHIP
  inv_msg <- msgs[grepl("Effective inverse", msgs)]
  expect_true(length(inv_msg) > 0L)
  expect_true(any(grepl("FIP", inv_msg)))
  # ERA and WHIP should NOT appear in the "Effective inverse" line
  expect_false(any(grepl("ERA", inv_msg)))
  expect_false(any(grepl("WHIP", inv_msg)))
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-7: Layer-1 — validation abort on unknown element
# ---------------------------------------------------------------------------

test_that("Layer-1 explicit arg aborts on element not in scoring_categories", {
  lh <- .lh_era_whip_fip()
  expect_error(
    sgp_denominators(
      lh,
      scoring_categories = c("ERA", "WHIP", "FIP"),
      inverse_categories = c("FIP", "NOSUCHCAT")
    ),
    class = "rotostats_error_invalid_inverse_categories"
  )
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-8: Invalid `config` arg aborts
# ---------------------------------------------------------------------------

test_that("sgp_denominators aborts when config is not a league_config object", {
  lh <- .lh_era_whip()
  expect_error(
    sgp_denominators(
      lh,
      scoring_categories = c("ERA", "WHIP"),
      config             = list(x = 1)
    ),
    class = "rotostats_error_invalid_parameter"
  )
})

# ---------------------------------------------------------------------------
# TC-SGP-INV-9: Legacy back-compat — existing ERA/WHIP behavior unchanged
# ---------------------------------------------------------------------------

test_that("legacy ERA/WHIP default behavior is preserved (back-compat)", {
  lh <- .lh_era_whip()
  d <- suppressMessages(
    sgp_denominators(lh, scoring_categories = c("ERA", "WHIP"))
  )
  expect_true(is.numeric(d$denominators))
  expect_named(d$denominators, c("ERA", "WHIP"), ignore.order = TRUE)
  expect_true(all(is.finite(d$denominators)))
  expect_true(all(d$denominators > 0))
})
